#!/bin/bash
#cores
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
amarelo="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaa="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoo="\033[1;31m"
verdee="\033[1;32m"
amareloo="\033[1;33m"
azull="\033[4;34m"
rosa="\033[1;35m"
cyann="\033[2;36m"
branco="\033[1;37m"
cyann="\033[2;36m"
# BY: Glemysson
clear
echo -e "Digite sua host que deseja adicionar
ao /etc/payloads"
read -p ": " host
echo ".$host" >>/etc/payloads
sleep 2
echo "Sua host foi adiconada com sucesso"
sleep 2
echo "Saindo..."
exit
