#!/bin/bash
# cor
b="\033[1;37m"
v="\033[1;32m"
Ver="\033[1;31m"
if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Pqp Tu Nao Eh Usuario root vey,"
    sleep 2
    echo "Pra Virar user root Basta Digitar ( sudo su )"
	fi
fi
clear
IP=$(cat /etc/IPMENU)
echo -e "$b=====================>>>"$v"CONFVPS 3.0"$b"<<<======================"
echo -e " \033[1;37m      CONFVPS V: FINAL ["$Ver"By: JORGE BARBA"$b"]\033[0m"
echo -e "                 $v Att: 05/08/2017"
echo -e "\033[1;37mElija  una opcion:    \033[1;37mPara Sair opcion  0\033[1;33m"
echo -e "\033[1;37mSu IP \033[1;37m(\033[1;32m$IP\033[1;37m)"
echo -e "                    $b["$v"0"$b"]$Ver Sair"
echo ""
echo -e "$b["$v"01$b]$Ver INSTALAR SQUID               $b["$v"14$b]$Ver DESISTALAR MODULOS"
echo -e "$b["$v"02$b]$Ver INSTALAR DROPBEAR            $b["$v"15$b]$Ver ALTERAR SENHA ROOT"
echo -e "$b["$v"03$b]$Ver INSTALAR OPENVPN             $b["$v"16$b]$Ver RENICIAR VPS"
echo -e "$b["$v"04$b]$Ver INSTALAR SSL                 $b["$v"17$b]$Ver ATUALIZAR CONFVPS"
echo -e "$b["$v"05$b]$Ver ADMINISTRAR USUARIOS         $b["$v"18$b]$Ver OCULTAR IP DO MENU"
echo -e "$b["$v"06$b]$Ver BOT DE TELEGRAM"             $b["$v"19$b]$Ver GENERADOR DE CC"
echo -e "$b["$v"07$b]$Ver PAYLOAD BRUTE FORCE"         $b["$v"20$b]$Ver
echo -e "$b["$v"08$b]$Ver MONITOR SSH
echo -e "$b["$v"09$b]$Ver SPEEDTEST"
echo -e "$b["$v"10$b]$Ver ADD BANNER"
echo -e "$b["$v"11$b]$Ver ADDHOST"
echo -e "$b["$v"12$b]$Ver REMOVER CONFVPS"
echo -e "$b["$v"13$b]$Ver UPDATE VPS"
echo -e "$b===========================>>>""<<<==========================="
echo -e "$Ver"
echo -e "$b["$v"Escolha uma opcao"$b"]";read -p "└─>> "  opcao
case $opcao in
1)
squid3-installer
;;
2)
dropbear-installer
;;
3)
openvpn.sh
;;
4)
ssl.sh
;;
5)
users-gen
;;
6)
ADMbot.sh
;
;
7)
paysend.sh
;;
8)
monitor-ssh
;;
9)
speedtest.py
;;
0)
exit
;;
10)
banner
;;
11)
addhost
;;
12)
unistaller-confvps
;;
13)
update-confvps
;;
14)
unistaller-modulos
;;
15)
alterar-senha
;;
16)
reboot-vps
;;
17)
update-confvps
;;
18)
generadorbarba.sh
;;



