#!/bin/bash

# cor

b="\033[1;33m"

v="\033[1;32m"

Ver="\033[0;34m"

m="\033[0;34m"

if [ $(id -u) -eq 0 ]

then

	clear

else

	if echo $(id) |grep sudo > /dev/null

	then

	clear

	echo "usted no  es un usuario root"

sleep 2

echo "PARA INSTALAR ROOT SOLO DIGITE ( sudo su )"

	fi

fi

clear

IP=$(cat /etc/IPMENU)

echo -e "$b=====================>>>"$v"BIENVENIDOS"$b"<<<======================"

IP=$(cat /etc/IPMENU)

echo -e "$b=====================>>>"$v"VERSION1.1"$b"<<<======================"

echo -e " \033[1;37m VPS-BARBA V:1.1 ["$Ver"CREADO POR @Jorge_Barba"$b"]\033[0m"

echo -e "\033[1;37mSeleccione una de las  opciones: \033[1;37mPara Salír opcióno 0\033[1;33m"

echo -e "\033[1;37mSu IP \033[1;37m(\033[1;32m$IP\033[1;37m)"

echo -e " $b["$v"0"$b"]$Ver Sair"

echo ""

echo -e "$b["$v"01$b]$Ver MENU DE USUARIOS $b["$v"11$b]$Ver ADMINISTRAR VPS"

echo -e "$b["$v"02$b]$Ver HERRAMIENTAS     $b["$v"12$b]$Ver INSTALAR SQUID"

echo -e "$b["$v"03$b]$Ver DROPBEAR         $b["$v"13$b]$Ver SSL && SHADOWNSNOCK"

echo -e "$b["$v"04$b]$Ver INSTALAR OPENVPN $b["$v"14$b]$Ver ATUALIZAR VPS-BARBA"

echo -e "$b["$v"05$b]$Ver USUARIOS ONLINE  $b["$v"15$b]$Ver GENERADOR DE CC"

echo -e "$b["$v"06$b]$Ver SERVIDOR APACHE  $b["$v"16$b]$Ver OCULTAR IP"

echo -e "$b["$v"07$b]$Ver VERIFICACION     $b["$v"17$b]$Ver CREDITOS"

echo -e "$b["$v"08$b]$Ver REMOVER VPS-BARBA"

echo -e "$b["$v"09$b]$Ver PAYLOAD BRUTE FORCE"

echo -e "$b["$v"10$b]$Ver BUSCADOR DE HOST"

echo -e "$b=====================>>>"$v"VPS-BARBA"$b"<<<======================"

echo -e "$Ver"

echo -e "$b["$v"Selecciona una opcion "$b"]";read -p "└─>> " opcao

case $opcao in

1)
users-gen


;;

2)
adm3


;;

3)
dropbear-installer


;;

4)
vpn-installer

;;

5)
monitor-ssh

;;

6)
banner

;;

7)

banner

;;

8)
unistallerSSnfvps

;;

9)
paysnd.sh 


;;

0)

exit

;;

10)
verifica
;;

11)
unistaller-modulos

;;

12)
squid3-installer
;;

13)
ssl.sh 

;;

14)
vps-update

;;

15)

ocultar-ip 

;;

esac

