#!/bin/bash
cabecaho
echo -e "\033[0;32m=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞\033[0m"
echo -e "\033[1;32m ∆\033[1;32m¡BIENVENIDO AL MENÚ!"
echo -e "\033[0;32m=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞\033[0m"
echo -e "$b["$v"01$b]$Ver INSTALAR SQUID     $b["$v"11$b]$Ver HERRAMIENTAS"

echo -e "$b["$v"02$b]$Ver INSTALAR DROPBEAR  $b["$v"12$b]$Ver GESTIÓNAR VPS"

echo -e "$b["$v"03$b]$Ver INSTALAR OPENVPN   $b["$v"13$b]$Ver RENICIAR VPS"

echo -e "$b["$v"04$b]$Ver INSTALAR  SSL      $b["$v"14$b]$Ver ATUALIZAR VPS-BARBA"

echo -e "$b["$v"05$b]$Ver MENU DE USER       $b["$v"15$b]$Ver OCULTAR IP DE MENU"

echo -e "$b["$v"06$b]$Ver SPEEDTEST"

echo -e "$b["$v"07$b]$Ver AÑADIR  BANNER"

echo -e "$b["$v"08$b]$Ver ADDHOST"

echo -e "$b["$v"09$b]$Ver REMOVER VPS-BARBA"

echo -e "$b["$v"10$b]$Ver UPDATE VPS"
echo -e "\033[0;32m=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞\033[0m"
echo -e "$b["$v"Seleccione una opcion"$b"]";read -p "└─>> " opcao

case $opcao in

1)

squid3-installer

;;

2)

dropbear-installer

;;

3)

vpn-installer


;;

4)

SSL


;;

5)

users-agen tcc

;;

6)

speedtest.py

;;

7)

banner

;;

8)

addhost

;;

9)

unistaller-confvps

;;

0)

exit

;;

10)

vps-update

;;

11)

adm3

;;

12)

users-gen


;;

13)

vpn-installer

;;

14)

users-gen

;;

15)

monitor-ssh


esac

